---
defects: 
      'v_O':
       - 3
       - 'v_O_++'
       - 'v_O_+' 
       - 'v_O'
      'v_Li':
       - 3
       - 'v_Li'
       - 'v_Li_-'
      'Li_i':
       - 1
       - 'Li_i'
       - 'Li_i_+'
      'O_i':
       - 1
       - 'O_i'
       - 'O_i_-'
      'v_La':
       - 2
       - 'v_La_---'
      'v_Zr':
       - 1
       - 'v_Zr_----'
      'Zr_i':
       - 1
       - 'Zr_i'
       - 'Zr_i_+'
       - 'Zr_i_++'
       - 'Zr_i_+++'
       - 'Zr_i_++++'
      'Zr_Li_tet':
       - 1
       - 'Zr_Li_tet'
       - 'Zr_Li_tet_+'
       - 'Zr_Li_tet_++'
       - 'Zr_Li_tet_+++'
      'Zr_Li':
       - 2
       - 'Zr_Li'
       - 'Zr_Li_+'
       - 'Zr_Li_++'
       - 'Zr_Li_+++'
      'Zr_La':
       - 2
       - 'Zr_La'
       - 'Zr_La_+'
      'La_Zr':
       - 2
       - 'La_Zr'
       - 'La_Zr_-'
      'Li_La':
       - 2
       - 'Li_La'
       - 'Li_La_-'
       - 'Li_La_--'
      'Li_Zr':
       - 1
       - 'Li_Zr'
       - 'Li_Zr_-'
       - 'Li_Zr_--' 
       - 'Li_Zr_---'       
e_vbm: 3.647
nelect: 544
e_gap: 5.904
spin_polarised: True
iccs:
     1: 0.054923318940534864
     2: 0.21969327576213946
     3: 0.4943098704648138
     4: 0.8787731030485578
     5: 1.3730829735133716
     6: 1.9772394818592551
     7: 2.6912426280862087 
potals:
    v_O_++: 0.034
    v_O_+: -0.044
    v_O: 0
    v_Li: 0
    v_Li_-: -0.032
    Li_i : 0
    La_Zr: 0
    La_Zr_- : 0.10350315789471409
    Li_i_+ : 0.03406739130434033
    O_i : 0
    O_i_- : -0.004940000000004829
    v_La_--- : -0.3375894117647178
    v_Zr_---- : -0.2980481927711054
    Zr_La : 0
    Zr_La_+ : -0.08226595744680765
    Zr_Li : 0
    Zr_Li_+ : 0.1214978947368408
    Zr_Li_++ : 0.13771505376341509
    Zr_Li_+++ : 0.144820430107508
    Zr_Li_tet : 0
    Zr_Li_tet_+ : 0.18679101123593966
    Zr_Li_tet_++ : 0.13769032258063163
    Zr_Li_tet_+++ : 0.18368409090908244
    Zr_i : 0
    Zr_i_+ : 0.21727624999999762
    Zr_i_++ : 0.23355232558137118
    Zr_i_+++ : 0.23345833333332422
    Zr_i_++++ : 0.2488537500000021
    Li_Zr : 0
    Li_Zr_- : -0.004041111111121154
    Li_Zr_-- : -0.017765555555556034
    Li_Zr_--- : -0.026111111111113416
    Li_La : 0
    Li_La_- : -0.06163763440859782
    Li_La_-- : -0.06490326086959186
    La_Li : 0
    La_Li_+ : 0.4787106060606092
    La_Li_++ : 0.480425000000003
ue: 
    v_O_++: 0
    v_O_+: 1
    v_O: 0
    v_Li: 1
    v_Li_-: 0
    v_Zr_---- : -0.0
    v_La_--- : 0.0
    v_Li_- : -0.0
    v_Li : 1.0
    v_O : -0.0
    v_O_+ : 1.0
    v_O_++ : 0.0
    Zr_La : 1.0
    Zr_La_+ : -0.0
    La_Zr : 1.0
    La_Zr_- : 0.0
    Zr_Li : 1.0
    Zr_Li_+ : 2.0
    Zr_Li_++ : 1.0
    Zr_Li_+++ : 0.0
    Zr_Li_tet : 3.0
    Zr_Li_tet_+ : 2.0
    Zr_Li_tet_++ : 1.0
    Zr_Li_tet_+++ : -0.0
    Li_i : 1.0
    Li_i_+ : 0.0
    O_i : -0.0
    O_i_- : 0.0
    Zr_i : -0.0
    Zr_i_+ : -0.0
    Zr_i_++ : -0.0
    Zr_i_+++ : 1.0
    Zr_i_++++ : 0.0
    Li_Zr : -0.0
    Li_Zr_- : 2.0
    Li_Zr_-- : 1.0
    Li_Zr_--- : 0.0
    Li_La_- : 0.0
    Li_La_-- : 0.0
    Li_La : 0.0
    La_Li_+ : 0.0
    La_Li_++ : 0.0
    La_Li : 0.0
          
    
